# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
server:
  port: 1111   # HTTP (Tomcat) port